{% set version = "0.1.13" %}
# obtained sha256 with "shasum -a -b" command
{% set sha256 = "dd3a48dd56977bfd92dee2c8b612ad14a1d19f171c77b8a48ecfb68b5de23e5d" %}

package:
  name: xo
  version: {{ version }}

source:
  fn: xo-{{ sha256 }}.tar.gz
  url: https://github.com/scopatz/xo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - lazyasd
    - urwid >=1.1.1
    - pygments >=1.6

test:
  commands:
    - xo --help

about:
  home: http://exofrills.org/
  license: WTFPL v2
  summary: "exofrills text editor"

extra:
  recipe-maintainers:
    - scopatz
